-- 이 스크립트를 애플리케이션 배포 전에 실행해야 합니다.
-- 기존 회원은 서비스 연속성을 위해 APPROVED로 이관하고, 이후 앱에서 생성되는 회원은 PENDING입니다.
ALTER TABLE MASK_MEMBER ADD (
    APPROVAL_STATUS VARCHAR2(20),
    REVIEWED_BY_MEMBER_ID NUMBER(19),
    REVIEWED_BY_NAME VARCHAR2(50),
    REVIEWED_AT TIMESTAMP
);

UPDATE MASK_MEMBER
SET APPROVAL_STATUS = 'APPROVED'
WHERE APPROVAL_STATUS IS NULL;

ALTER TABLE MASK_MEMBER MODIFY (APPROVAL_STATUS VARCHAR2(20) NOT NULL);

ALTER TABLE MASK_MEMBER ADD CONSTRAINT CK_MASK_MEMBER_APPROVAL
CHECK (APPROVAL_STATUS IN ('PENDING', 'APPROVED', 'REJECTED'));

CREATE INDEX IX_MEMBER_APPR_CREATED
ON MASK_MEMBER (APPROVAL_STATUS, CREATED_AT);

COMMIT;
